(setq mac-command-modifier 'meta)
(setq mac-option-modifier 'super)

;; (key-chord-define-global "`j" 'avy-goto-char)
;; (key-chord-define-global "`k" 'avy-goto-word1-above)
;; (key-chord-define-global "`j" 'avy-goto-word-0-below)
(key-chord-define-global "jk" nil)
(key-chord-define-global "jl" nil)
(key-chord-define-global "jj" nil)
(key-chord-define-global "xx" nil)
(key-chord-define-global "yy" nil)
(key-chord-define-global "uu" nil)

(prelude-require-packages '(evil-escape linum-relative))

(evil-escape-mode 1)
(setq-default evil-escape-key-sequence "jh")

(define-key evil-normal-state-map (kbd "TAB") 'evil-buffer)
(define-key evil-normal-state-map "s" nil)
(define-key evil-normal-state-map (kbd "s s") 'avy-goto-char)
(define-key evil-normal-state-map (kbd "s k") 'avy-goto-line-above)
(define-key evil-normal-state-map (kbd "s j") 'avy-goto-line-below)
(define-key evil-normal-state-map (kbd "s b") 'avy-goto-word-0-above)
(define-key evil-normal-state-map (kbd "s w") 'avy-goto-word-0-below)
